### PR TITLE
Build with optional catkin support

### PR DESCRIPTION
**Pull request by dvj**
Greatly simplifies using this project as-is by removing the need to have catkin installed.

Catkin will be used if available.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks @dvj, I'll give this a try as soon as I have time.

**Comment by wjwwood** [comment]
One issue I can already foresee is that without `catkin` no `serial-config.cmake` file will be generated or installed, making it difficult to use the result from another CMake package.

Having to write my own CMake config file or module file was the reason I had put off removing `catkin` as a required dependency.

**Comment by dvj** [comment]
That's a fair point. I'll try to take a crack at it. With only one target it shouldn't be too bad.

Adding support to run the tests without catkin would also be a consideration.

**Comment by wjwwood** [comment]
I'm going to decline this pr, though I do appreciate your effort trying to get this change made.

I'm going to convert to pure CMake in the following version, leaving this version using catkin unconditionally.

Thanks again.

**Pull request closed without merging**
